spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3309/norja?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: norja
    password: 1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000